apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: updatecontext
spec:
  version: "v0.1.4"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.4/updatecontext_linux_amd64.tar.gz
    sha256: "ba4ef1a454d1444a7461da33faca605b633a001a25ad22d5213b3dbe99c868a6"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.4/updatecontext_darwin_amd64.tar.gz
    sha256: "08e5a72a413ad46f66ffef84dd590dc9fd6e7f5b9cb20ccfbfd541ccacdd0757"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.4/updatecontext_windows_amd64.zip
    sha256: "3e99817d1ec63528f4b44a02b92cbde44eee25f0932a96e8f6e45bc50786c1ed"
    files:
    - from: "updatecontext.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext.exe"
  shortDescription: A new plugin
  homepage: https://github.com/borisputerka/updatecontext
  caveats: |
    Usage:
      $ kubectl updatecontext

    For additional options:
      $ kubectl updatecontext --help

  description: |
    This is a new plugin for creating contexts in kubeconfig
