apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: updatecontext
spec:
  version: "v0.1.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.1/updatecontext_linux_amd64.tar.gz
    sha256: "1b8f073abc844b258a01780fc5dab15ef01cbdc06cea7e9a1bdd14f49927cbc3"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.1/updatecontext_darwin_amd64.tar.gz
    sha256: "f366edbac6b02d02140ffc1ecbd2f2e33aed5e65b0250f1cab777ed9fcb856ff"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.1/updatecontext_windows_amd64.zip
    sha256: "0bd049c9030219225f3d053c694b454628843f31bd25542054845d5f1a58a3ff"
    files:
    - from: "updatecontext.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext.exe"
  shortDescription: A new plugin
  homepage: https://github.com/borisputerka/updatecontext
  caveats: |
    Usage:
      $ kubectl updatecontext

    For additional options:
      $ kubectl updatecontext --help

  description: |
    This is a new plugin for creating contexts in kubeconfig
