apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: updatecontext
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/archive/v0.1.0.tar.gz
    sha256: "57063e5db5a1ed933f52f92ef4bb59fb7f197a375cb4aa3a6ad039f663be777e"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.4/updatecontext_darwin_amd64.tar.gz
    sha256: "60adb5ebdef9896ef042ad053b1008ece180b0afd2416124eae2b34b61c6eb94"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/archive/v0.1.0.tar.gz
    sha256: "57063e5db5a1ed933f52f92ef4bb59fb7f197a375cb4aa3a6ad039f663be777e"
    files:
    - from: "updatecontext.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext.exe"
  shortDescription: A new plugin
  homepage: https://github.com/borisputerka/updatecontext
  caveats: |
    Usage:
      $ kubectl updatecontext

    For additional options:
      $ kubectl updatecontext --help
      or https://github.com/borisputerka/updatecontext/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
