apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: updatecontext
spec:
  version: "v0.1.2"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.2/updatecontext_linux_amd64.tar.gz
    sha256: "3302195a0b801825103c519c7618d821969d4438362f7d38b7b5768c5ee90428"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.2/updatecontext_darwin_amd64.tar.gz
    sha256: "196b065591137db479facfdffcb32ef9b475e04107222bb98124994057059e52"
    files:
    - from: "updatecontext"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/borisputerka/updatecontext/releases/download/v0.1.2/updatecontext_windows_amd64.zip
    sha256: "7900b045ed2f3ac59f48904e1e32941c5bb9a51d09b377014fc3c1e39564574d"
    files:
    - from: "updatecontext.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "updatecontext.exe"
  shortDescription: A new plugin
  homepage: https://github.com/borisputerka/updatecontext
  caveats: |
    Usage:
      $ kubectl updatecontext

    For additional options:
      $ kubectl updatecontext --help

  description: |
    This is a new plugin for creating contexts in kubeconfig
